/****************************************************************************
**
** GENERATED BY SOHAG DEVELOPER FOR POSTGRESQL
** Visit Us: http://sohag-developer.com/
**
****************************************************************************/

#include "employees.h"
#include <QApplication>


int main(int argc, char *argv[])
{
    QApplication sohag(argc, argv);
	
    Employees sohagDev;
    sohagDev.show();

    return sohag.exec();
} 
